apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Leave as true until LDAP has been successfully set up - enables manual login
  admin.enabled: "true"
  url: https://argo.crcd.pitt.edu
  dex.config: |
    connectors:
    - type: ldap
      name: LDAP
      id: ldap
      config:
        host: "sam-ldap-prod-01.cssd.pitt.edu:389"
        insecureNoSSL: false
        insecureSkipVerify: true
        startTLS: true
        usernamePrompt: username
        userSearch:
          baseDN: "dc=frank,dc=sam,dc=pitt,dc=edu"
          username: uid
          idAttr: uid
          emailAttr: uid
        groupSearch:
          baseDN: "ou=groups,dc=frank,dc=sam,dc=pitt,dc=edu"
          userMatchers:
          - userAttr: uid
            groupAttr: member
          nameAttr: name
