apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:none
  policy.csv: |
    # --- Platform admins: full control over projects, appsets, repos, clusters ---
    p, role:platform-admin, projects, *, *, allow
    p, role:platform-admin, applicationsets, *, */*, allow
    p, role:platform-admin, applications, *, */*, allow
    p, role:platform-admin, repositories, *, *, allow
    p, role:platform-admin, write-repositories, *, *, allow
    p, role:platform-admin, clusters, *, *, allow
    p, role:platform-admin, accounts, *, *, allow
    p, role:platform-admin, certificates, *, *, allow
    p, role:platform-admin, gpgkeys, *, *, allow
    p, role:platform-admin, logs, get, */*, allow
    p, role:platform-admin, exec, create, */*, allow

    g, sam_frank_admins_posix, role:platform-admin
  scopes: '[groups]'