apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: sectigo-issuer
spec:
  acme:
    server: "https://acme.enterprise.sectigo.com"
    email: "<acme-email>"
    privateKeySecretRef:
      name: sectigo-issuer-account-key
    externalAccountBinding:
      keyID: "f735f307dc39dcf54fd0017bfe0f314a"
      keySecretRef:
        name: sectigo-eab-credentials
        key: eab_hmac
    solvers:
      - http01:
          ingress:
            ingressClassName: contour
