apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: sectigo-eab-credentials
  namespace: admin-cert-manager
spec:
  vaultAuthRef: cert-manager-vso-auth
  mount: admin
  type: kv-v2
  path: cert-manager
  refreshAfter: 1h
  destination:
    name: sectigo-eab-credentials
    create: true
    type: Opaque
