apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-cert-manager-reader
  namespace: admin-cert-manager
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  namespace: admin-cert-manager
spec:
  address: https://vault.crcd.pitt.edu
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cert-manager-vso-auth
  namespace: admin-cert-manager
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: admin-cert-manager-reader
    serviceAccount: admin-cert-manager-reader
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: sectigo-eab-credentials
  namespace: admin-cert-manager
spec:
  vaultAuthRef: cert-manager-vso-auth
  mount: admin
  type: kv-v2
  path: cert-manager
  refreshAfter: 1h
  destination:
    name: sectigo-eab-credentials
    create: true
    type: Opaque
