apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: admin-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "admin-nginx-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/admin/data/nginx/test"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/admin/data/nginx/test" -}}
          export TEST_VALUE="{{ .Data.data.value }}"
          {{- end }}
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-run-as-non-root: "true"
        vault.hashicorp.com/agent-set-security-context: "true"
        vault.hashicorp.com/tls-secret: "tls-ca"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
    spec:
      serviceAccountName: admin-nginx-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:latest
          command:
            - /bin/sh
            - -c
            - |
              . /vault/secrets/config && nginx -g 'daemon off;'
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 101
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
