apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-tenants
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/pitt-crc/k8s-manifests.git
        revision: main
        directories:
          - path: argocd/tenants/*
  template:
    metadata:
      name: "tenant-{{ .path.basenameNormalized }}"
      namespace: argocd
    spec:
      project: argocd
      source:
        repoURL: https://github.com/pitt-crc/k8s-manifests.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - ServerSideApply=true
