apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
  - name: argo-cd
    version: 9.4.17
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml

resources:
  - project.yaml
  - application.yaml
  - tenants/**
