configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
    url: "https://argo.crcd.pitt.edu"
  params:
    server.tls.secret.name: argocd-tls

server:
  service:
    type: LoadBalancer
    loadBalancerIP: 10.7.84.16

  certificate:
    enabled: true
    secretName: argocd-tls
    issuer:
      name: sectigo-issuer
      kind: ClusterIssuer
    domain: argo.crcd.pitt.edu
