apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/pitt-crc/k8s-manifests.git
        revision: main
        directories:
          - path: apps/*
            exclude: false
  template:
    metadata:
      name: "{{ .path.basenameNormalized }}"
      namespace: argocd
    spec:
      project: management
      source:
        repoURL: https://github.com/pitt-crc/k8s-manifests.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "management-{{ .path.basenameNormalized }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
