apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: admin
  namespace: admin-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - https://github.com/pitt-crc/k8s-manifests.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: admin-*
