apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: admin
  namespace: admin-argocd
spec:
  sourceRepos:
    - https://github.com/pitt-crc/k8s-manifests.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: admin-*

  # Allow required cluster-scoped resources
  clusterResourceWhitelist:

    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition

    - group: rbac.authorization.k8s.io
      kind: ClusterRole

    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration

    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration

    - group: cert-manager.io
      kind: ClusterIssuer

    - group: ""
      kind: Namespace

  # Allow all namespaced resources
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
