apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: admin-apps
  namespace: argocd
spec:
  description: Manages cluster-wide administrative applications from the /apps directory.
  sourceRepos:
    - https://github.com/pitt-crc/k8s-manifests.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: admin-*
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
  roles:
    - name: tenant
      policies:
        - p, proj:admin-apps:tenant, applications, get, admin-apps/*, allow
        - p, proj:admin-apps:tenant, applications, sync, admin-apps/*, allow
        - p, proj:admin-apps:tenant, applications, action/*, admin-apps/*, allow
        - p, proj:admin-apps:tenant, logs, get, admin-apps/*, allow
      groups:
        - sam_frank_admins_posix
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: admin-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/pitt-crc/k8s-manifests.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: "admin-{{ .path.basenameNormalized }}"
      namespace: argocd
    spec:
      project: admin-apps
      source:
        repoURL: https://github.com/pitt-crc/k8s-manifests.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "admin-{{ .path.basenameNormalized }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
