apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: crcd
  namespace: argocd
spec:
  description: CRCD application deployments.
  sourceRepos:
    - '*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: crcd-*
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  roles:
    - name: tenant
      policies:
        - p, proj:crcd:tenant, applications, get, crcd/*, allow
        - p, proj:crcd:tenant, applications, sync, crcd/*, allow
        - p, proj:crcd:tenant, applications, action/*, crcd/*, allow
        - p, proj:crcd:tenant, logs, get, crcd/*, allow
      groups:
        - sam_frank_admins_posix
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crcd-dataverse
  namespace: argocd
spec:
  project: crcd
  source:
    repoURL: https://github.com/pitt-crc/dataverse.git
    targetRevision: main
    path: "manifests"
  destination:
    server: https://kubernetes.default.svc
    namespace: crcd-dataverse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crcd-lmas
  namespace: argocd
spec:
  project: crcd
  source:
    repoURL: https://github.com/pitt-crc/lmas-manifests.git
    targetRevision: main
    path: "manifests"
  destination:
    server: https://kubernetes.default.svc
    namespace: crcd-lmas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
