configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
  params:
    server.tls.secret.name: vault-tls

server:
  service:
    type: LoadBalancer

  certificate:
    enabled: true
    secretName: vault-tls
    issuer:
      name: sectigo-issuer
      kind: ClusterIssuer
    domain: vault.crcd.pitt.edu
